[package]
name = "url"
version = "0.1.0"
edition = "2024"

[dependencies]
sqlx = { version = "0.8.5", features=["runtime-tokio","postgres"] }
dotenv = "0.15.0"
uuid = { version = "1.2", features = ["v4"] }
tokio = { version = "1", features = ["full"] }
colored = "3.0.0"